import styles from '@/styles/Home.module.css';


export function Head() {
  return (
    <Head>
        <title>Create Next App Index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
