import { Header } from "src/components/Header/Index";
import { Mainsec } from "src/components/Mainsec/Index";
import Head from "next/head";
import styles from "src/styles/Home.module.css";



export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Mainsec page="about"/>
    </div>
  );
}
