import Head from "next/head";
import styles from "src/styles/Home.module.css";
import { Mainsec } from "src/components/Mainsec/Index";
import { Header } from "src/components/Header/Index";


export default function About({
  count,
  isShow,
  handleClick,
  handleDisplay,
  text,
  array,
  handleChange,
  handleAdd,
}) {
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />

      { isShow ? <h1>{ count }</h1> : null }
      <button onClick={handleClick}>btn</button>
      <button
        onClick={handleDisplay}
      >
        { isShow ? "非表示" : "表示" }
      </button>

      <input
        type="text"
        value={text}
        onChange={handleChange}
      />
      <button onClick={handleAdd}>追加</button>
      {/* <ul>
        {array.map(item => {
          return (
            <li key={item}>{item}</li>
          )
        })}
      </ul> */}

      <Mainsec page="about"/>
    </div>
  );
}
