import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { HeaderLogo } from "@/components/HeaderLogo";
import { Links } from "@/components/Links";
import { Imgs } from "@/components/Imgs";
import { Headline } from "@/components/Headline";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Headline
            page="about"
            code={<code className={styles.code}>pages/{props.page}</code>}
            // onClick={() => alert('click!!')}
          />

          <HeaderLogo />
        </div>

        <Imgs />

        <Links />
      </main>
    </>
  );
}
