import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { HeaderLogo } from '../components/HeaderLogo';
import { Links } from '@/components/Links';
import { Images } from '@/components/images';
import { Headline } from '@/components/Headline';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App Index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={`${styles.description} ${styles.title}`}>
          <Headline title="Index Page" page="index" />

          <HeaderLogo />
        </div>
        <Images />

        <Links />
      </main>
    </>
  )
}
