import Head from "next/head";
import { Mainsec } from '@/components/Mainsec';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mainsec page="index"/>
    </>
  )
}
